import { request } from 'http'
import Head from 'next/head'
import Header from "../components/Header"
import Nav from "../components/Nav"
import Results from "../components/Results"
import requests from '../utils/requests'

export default function Home({ results }: { results : []}) {
  
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       
       <Header />

        <Nav />

       <Results results={results} /> 

    </div>
  )
}


export async function getServerSideProps(context : any) {
  const genere = context.query.genre;
  const url = `https://api.themoviedb.org/3${
    requests[genere]?.url || requests.fetchTrending.url
  }`;
  console.log(url);
  const request = await fetch(url).then((res) => res.json());
  //.then((res) => console.log("re", res))
  //.catch((err) => console.log("err", err));
  return {
    props: {
      results: request?.results ?? null,
    },
  };
}